// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cmxqgvhxmxhkfnzatpny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNteHFndmh4bXhoa2ZuemF0cG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NDQ4ODQsImV4cCI6MjA4NzAyMDg4NH0.S8Xreva2mecx0EIV7APcTuwXEE7F_OisBEvNUBF6--g";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);